# Generated by Django 5.2.5 on 2025-09-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_alter_user_profile_address_alter_userpost_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
