# Generated by Django 5.2.5 on 2025-09-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='media/profile_img/profilepic.png', null=True, upload_to='profile_img/%Y/%m/%d/'),
        ),
    ]
